const Map<String, String> enUS = {
  "إنتظر قليلاً...": "Please wait...",
  "إعدادات العملة": "Currency Settings",
  "الليرة السورية": "Syrian Pound",
  "الدولار الأمريكي": "US Dollar",
  "سيتم عرض جميع الأسعار بالعملة المحددة. يمكنك تغييرها في أي وقت.": "All prices will be displayed in the selected currency. You can change it anytime.",
  
  'إضافة إعلان جديد': 'Add New Ad',
  'بيانات المعلن': 'Advertiser Data',
  'سيتم عرض هذه البيانات للتواصل معك': 'This data will be visible for contact',
  'لا توجد بيانات معلن متاحة': 'No advertiser data available',
  'اختر بيانات المعلن': 'Select Advertiser Data',
  'تفاصيل الإعلان': 'Ad Details',
  'عنوان الإعلان': 'Ad Title',
  'وصف الإعلان': 'Ad Description',
  'السعر': 'Price',
  'اختيار التصنيف': 'Select Category',
  'التصنيف الرئيسي': 'Main Category',
  'التصنيف الفرعي': 'Subcategory',
  'التصنيف الثانوي': 'Secondary Subcategory',
  'خصائص الإعلان': 'Ad Features',
  'أدخل': 'Enter',
  'نعم': 'Yes',
  'لا': 'No',
  'صور الإعلان': 'Ad Images',
  'إضافة صور': 'Add Images',
  'لم يتم إضافة أي صور': 'No images added',
  'الموقع الجغرافي': 'Geographical Location',
  'تحديد الموقع الحالي': 'Detect Current Location',
  'الإحداثيات:': 'Coordinates:',
  'اختر المدينة': 'Select City',
  'اختر المنطقة': 'Select Area',
  'نشر الإعلان': 'Publish Ad',
  'أنشئ بياناتك كمعلن': 'Create Your Advertiser Profile',
  'هذه البيانات ستظهر للمستخدمين عند نشر الإعلانات': 'This information will be visible to users when publishing ads',
  'شعار المعلن (اختياري)': 'Advertiser Logo (Optional)',
  'إضافة شعار': 'Add Logo',
  'اضغط على الدائرة لإضافة أو تغيير الشعار': 'Tap the circle to add or change logo',
  'اسم المعلن*': 'Advertiser Name*',
  'أدخل اسمك أو اسم المؤسسة': 'Enter your name or organization',
  'وصف المعلن (اختياري)': 'Advertiser Description (Optional)',
  'أدخل وصفًا مختصرًا عن نشاطك': 'Enter a brief description of your activity',
  'رقم الاتصال*': 'Contact Number*',
  'مثال: 00963XXXXXXXX': 'Example: 00963XXXXXXXX',
  'رقم الواتساب (اختياري)': 'WhatsApp Number (Optional)',
  'مثال: 00963XXXXXXXXXXXXXXXX': 'Example: 00963XXXXXXXXXXXXXXXX',
  'خطأ': 'Error',
  'فشل في حفظ البيانات:': 'Failed to save data:',
  'حفظ البيانات': 'Save Data',
  '* الحقول الإلزامية': '* Required fields',
  'تعديل بيانات المعلن': 'Edit Advertiser Data',
  'قم بتحديث بياناتك ليظهر للمستخدمين بشكل صحيح': 'Update your data to display correctly to users',
  'تغيير الشعار': 'Change Logo',
  'اضغط على الدائرة لتغيير الشعار': 'Tap the circle to change logo',
  'إنشاء حساب جديد': 'Create New Account',
  'انضم إلينا الآن وتمتع بجميع الميزات الحصرية': 'Join us now and enjoy all exclusive features',
  'البريد الإلكتروني': 'Email',
  'رمز التحقق': 'Verification Code',
  'كلمة المرور': 'Password',
  'أدخل بريدك الإلكتروني': 'Enter your email',
  'سيتم إرسال رمز التحقق إلى بريدك الإلكتروني للتأكد من ملكيته': 'A verification code will be sent to your email to confirm ownership',
  'إرسال رمز التحقق': 'Send Verification Code',
  'أدخل رمز التحقق': 'Enter Verification Code',
  'تم إرسال رمز مكون من 6 أرقام إلى ': 'A 6-digit code has been sent to ',
  'لم تستلم الرمز؟': "Didn't receive the code?",
  'إعادة الإرسال': 'Resend',
  'تحقق من الرمز': 'Verify Code',
  'تغيير البريد الإلكتروني': 'Change Email',
  'أنشئ كلمة مرورك': 'Create Your Password',
  'كلمة المرور يجب أن تحتوي على 6 أحرف على الأقل': 'Password must contain at least 6 characters',
  'كلمة المرور صالحة': 'Valid Password',
  'لاحقًا': 'Later',
  'الإنشاء': 'Create',
  'العودة': 'Back',
  'مبروك لقد تم إنشاء حسابك بنجاح': 'Congratulations! Your account has been created successfully',
  'العودة للرئيسية': 'Return to Home',
  'بدء إضافة بيانات المعلن': 'Start Adding Advertiser Data',
  'اضف بيانات المعلن الظاهر للمستخدمين عند نشر الاعلانات\n(الاسم..الشعار(اختياري).رقم الاتصال ورقم الواتساب)': 'Add advertiser data visible to users when publishing ads\n(Name..Logo(optional).Contact number and WhatsApp)',
  'ابحث عن إعلان ...': 'Search for an ad...',
  'ع': 'Urg',
  
  'عاجل': 'Urgent',
  'عرض الإعلانات الجديدة آخر 24 ساعة': 'Show new ads from last 24 hours',
  'الرئيسية': 'Home',
  'البريد': 'Mail',
  'إعداداتي': 'My Settings',
  'خدماتنا': 'Our Services',
  'التصنيفات الرئيسية': 'Main Categories',
  'تسجيل الدخول': 'Login',
  'نسيت كلمة المرور؟': 'Forgot Password?',
  'أو': 'Or',
  'ليس لديك حساب؟': "Don't have an account?",
  'الحقول مطلوبة': 'Fields are required',
  'يرجى ملء جميع الحقول': 'Please fill all fields',
  'نجاح': 'Success',
  'تم تسجيل الدخول': 'Logged in successfully',
  'فشل': 'Failure',
  'خطأ في تسجيل الدخول': 'Login error',
  'لا توجد تصنيفات فرعية': 'No subcategories available',
  'عرض جميع الإعلانات': 'View All Ads',
  "الرجاء الإنتظار قليلاً": "Please wait a moment",
  'الخدمات المتاحة': 'Available Services',
  '١- من نحن': '1- About Us',
  '٢- الشروط والأحكام': '2- Terms & Conditions',
  '٣- الباقات': '3- Packages',
  '٤- آلية إضافة إعلان': '4- Ad Publishing Mechanism',
  '٥- التواصل معنا': '5- Contact Us',
  '٦- الإبلاغ عن مشكلة': '6- Report a Problem',
  'تعديل الإعلان': 'Edit Ad',
  'لا يوجد بيانات للإعلان': 'No ad data available',
  'يتم عرض البيانات الحالية للإعلان. قم بتعديل ما ترغب في تغييره': 'Current ad data is displayed. Modify what you want to change',
  'بدون اسم': 'Unnamed',
  'اعد اختيار اي تصنيف لتظهر الخصائص': 'Re-select any category to show features',
  'القيمة الحالية:': 'Current Value:',
  'إضافة صور جديدة': 'Add New Images',
  'الصور الحالية': 'Current Images',
  'معلومات': 'Information',
  'لا يمكن حذف الصور الحالية من هنا': 'Current images cannot be deleted from here',
  'الصور الجديدة': 'New Images',
  'لم يتم إضافة أي صور بعد': 'No images added yet',
  'تحديث الإعلان': 'Update Ad',
  'ليرة سورية': 'Syrian Pound',
  'تأكيد الحذف': 'Confirm Deletion',
  'هل أنت متأكد من حذف هذا الإعلان؟': 'Are you sure you want to delete this ad?',
  'إلغاء': 'Cancel',
  'حذف': 'Delete',
  'قبل': 'Before',
  'يوم': 'Day',
  'ساعة': 'Hour',
  'دقيقة': 'Minute',
  'مليون': 'Million',
  'ألف': 'Thousand',
  'إعلاناتي': 'My Ads',
  'إعلاناتي المنشورة': 'My Published Ads',
  'لا توجد إعلانات منشورة': 'No published ads',
  'الإعدادات': 'Settings',
  'الإعلانات': 'Ads',
  'إدارة الإعلانات': 'Manage Ads',
  'غير المنشورة': 'Unpublished',
  'حسابي': 'My Account',
  'معلوماتي': 'My Information',
  'تعيين كلمة المرور': 'Set Password',
  'المعلنين': 'Advertisers',
  'إدارة المعلنين': 'Manage Advertisers',
  'إضافة معلن جديد': 'Add New Advertiser',
  'المفضلات': 'Favorites',
  'مفضلاتي من الإعلانات': 'My Favorite Ads',
  'سجل المشاهدات الأخيرة': 'Recent View History',
  'المظهر': 'Appearance',
  'اللغة': 'Language',
  'العملة': 'Currency',
  'تسجيل خروج': 'Logout',
  'حذف الحساب': 'Delete Account',
  'ثيم التطبيق': 'App Theme',
  'تسجيل الخروج': 'Logout',
  'هل أنت متأكد أنك تريد تسجيل الخروج؟': 'Are you sure you want to logout?',
  'هل أنت متأكد أنك تريد حذف حسابك؟ هذه العملية لا يمكن التراجع عنها.': 'Are you sure you want to delete your account? This action cannot be undone.',
  'الأحدث إلى الأقدم': 'Newest to Oldest',
  'الأقدم إلى الأحدث': 'Oldest to Newest',
  'الأغلى إلى الأرخص': 'Highest to Lowest Price',
  'الأرخص إلى الأغلى': 'Lowest to Highest Price',
  'الأكثر مشاهدة': 'Most Viewed',
  'الأقل مشاهدة': 'Least Viewed',
  'ابحث في الإعلانات...': 'Search in ads...',
  'جميع الإعلانات': 'All Ads',
  'طريقة العرض': 'View Mode',
  'الفرز': 'Sort',
  'الفلترة': 'Filter',
  'لا توجد إعلانات مطابقة': 'No matching ads',
  'عرض طولي (مختصر)': 'List View (Compact)',
  'عرض طولي (مفصل)': 'List View (Detailed)',
  'عرض شبكي (مختصر)': 'Grid View (Compact)',
  'عرض شبكي (مفصل)': 'Grid View (Detailed)',
  'خيارات العرض': 'View Options',
  'إغلاق': 'Close',
  'خيارات الفرز': 'Sort Options',
  '1 كم': '1 km',
  '5 كم': '5 km',
  '10 كم': '10 km',
  '20 كم': '20 km',
  '50 كم': '50 km',
  'الخريطة': 'Map',
  'الموقع الجغرافي: غير مدخل': 'Location: Not entered',
  'خط العرض:': 'Latitude:',
  'أخذ الموقع': 'Get Location',
  'حدد نطاق البحث:': 'Set Search Radius:',
  'تطبيق البحث': 'Apply Search',
  "يرجى تحديد الموقع الجغرافي أولاً": "Please set location first",
  'تم البحث في نطاق': 'Searched within',
  'كم': 'km',
  'يجب تسجيل الدخول لإضافة إلى المفضلة': 'Login required to add to favorites',
  'تنبيه': 'Alert',
  'تاريخ النشر:': 'Publish Date:',
  'الخصائص': 'Features',
  'معلومات المعلن': 'Advertiser Info',
  'معلن': 'Advertiser',
  'واتساب': 'WhatsApp',
  'اتصال': 'Call',
  'تعذر فتح واتساب': 'Failed to open WhatsApp',
  'تعذر إجراء المكالمة': 'Failed to make call',
  'غير معروف': 'Unknown',
  'تطبيق الفلترة': 'Apply Filters',
  'إعادة تعيين': 'Reset',
  'الفترة الزمنية': 'Time Period',
  'المنطقة': 'Area',
  'المدينة': 'City',
  'الموقع': 'Location',
  'اختر': 'Select',
  'فلترة الإعلانات': 'Filter Ads',
  'آخر يومين': 'Last 2 Days',
  'آخر أسبوع': 'Last Week',
  'آخر شهر': 'Last Month',
  'آخر سنة': 'Last Year',
  'كل الاوقات': 'All Time',
  'تاريخ التسجيل': 'Registration Date',
  'حالة الحساب': 'Account Status',
  'الإعلانات المجانية': 'Free Ads',
  'مفعل': 'Active',
  'متبقية': 'Remaining',
  'إعدادت اللغة': 'Language Settings',
  'العربية': 'Arabic',
  'ملاحظة': 'Note',
  'تم تغيير اللغة': 'Language changed',
  'ملفات المعلنين': 'Advertiser Profiles',
  'ملفات المعلنين الخاصة بك': 'Your Advertiser Profiles',
  'اختر ملفًا لعرض تفاصيله أو قم بإنشاء ملف جديد': 'Select a profile to view details or create new',
  'إنشاء ملف جديد': 'Create New Profile',
  'لا توجد ملفات متاحة': 'No profiles available',
  'اختر ملف المعلن': 'Select Advertiser Profile',
  'ملف بدون وصف (ID:': 'Unnamed Profile (ID:',
  'ملف المعلن #': 'Advertiser Profile #',
  'معلومات الاتصال': 'Contact Information',
  'رقم الاتصال': 'Contact Number',
  'غير محدد': 'Not specified',
  'تعديل': 'Edit',
  "هل أنت متأكد أنك تريد حذف هذا الملف؟": "Are you sure you want to delete this profile?",
  'المفضلة': 'Favorites',
  'الإعلانات المفضلة': 'Favorite Ads',
  'لا توجد إعلانات في المفضلة': 'No favorite ads',
  'تمت الإزالة': 'Removed',
  'تمت إزالة الإعلان من المفضلة': 'Ad removed from favorites',
  'سجلات البحث': 'Search History',
  'هل أنت متأكد من حذف جميع سجلات البحث؟': 'Are you sure you want to clear all search history?',
  'حذف الكل': 'Clear All',
  'الإعلانات التي شاهدتها': 'Recently Viewed Ads',
  'لا توجد سجلات بحث': 'No search history',
  'تمت إزالة الإعلان من سجلات البحث': 'Ad removed from search history',
 
'مليون ل.س': 'Million SYP',
  'ألف ل.س': 'Thousand SYP',
  'ل.س': 'SYP',
'معلومات الإعلان': 'Ad Information',
  'مميز': 'Premium',
///////

  'من نحن': 'About Us',
  'تطبيق Stay in Me': 'Stay in Me App',
  'نرحب بكم في تطبيق Stay in Me - المنصة الرائدة في سوريا للاعلانات المبوبة، حيث نسعى لتقديم تجربة فريدة وسهلة لبيع وشراء مختلف السلع والخدمات.': 
      'Welcome to the Stay in Me app – Syria\'s leading classified ads platform, where we strive to provide a unique and seamless experience for buying and selling various goods and services.',
  'رؤيتنا': 'Our Vision',
  'أن نكون التطبيق الأول والوجهة المفضلة للاعلانات المبوبة في سوريا والوطن العربي، من خلال تحديثات مستمرة وخدمات مميزة.':
      'To become the premier app and preferred destination for classified ads in Syria and the Arab world, through continuous updates and premium services.',
  'مميزاتنا': 'Our Features',
  '• واجهة مستخدم سهلة ومبسطة\n• تصنيفات دقيقة ومتنوعة\n• إدارة فعالة للإعلانات\n• دعم فني متواصل\n• تحديثات مستمرة لتحسين التجربة':
      '• User-friendly, simplified interface\n• Accurate and diverse categories\n• Effective ad management\n• Continuous technical support\n• Regular updates to enhance the experience',
  'فريق العمل': 'Our Team',
  'نحن فريق من المطورين والمصممين والمختصين في التسويق الرقمي، نعمل بجهد لتطوير التطبيق باستمرار وتقديم أفضل تجربة للمستخدمين.':
      'We are a team of developers, designers, and digital marketing specialists working diligently to continually improve the app and deliver the best user experience.',
  '© 2025 Stay in Me. جميع الحقوق محفوظة': '© 2025 Stay in Me. All rights reserved',
  'آلية إضافة إعلان': 'Ad Creation Process',
  'لإضافة إعلان جديد في تطبيق Stay in Me، يرجى اتباع الخطوات التالية بدقة. هذه الآلية تضمن وصول إعلانك للجمهور المستهدف بفعالية.':
      'To create a new ad in the Stay in Me app, please follow these steps carefully. This process ensures your ad effectively reaches the target audience.',
  'تسجيل الدخول أو إنشاء حساب': 'Login or Create Account',
  '• يجب أن يكون لديك حساب مسجل في التطبيق\n• كل حساب له عدد محدود من الإعلانات المجانية\n• يمكنك الاشتراك في إحدى الباقات لزيادة عدد الإعلانات المسموحة':
      '• You must have a registered app account\n• Each account has a limited number of free ads\n• You can subscribe to a package to increase your ad allowance',
  '١': '1',
  '٢': '2',
  'إنشاء ملف المعلن': 'Create Advertiser Profile',
  '• كل إعلان يحتاج إلى ملف معلن مرتبط به\n• يمكنك إنشاء أكثر من ملف معلن لحساب واحد\n• ملف المعلن يحتوي على:\n   - الاسم الظاهر في الإعلان\n   - الشعار (صورة شخصية/لوجو)\n   - وصف مختصر عن المعلن\n   - معلومات التواصل':
      '• Every ad requires a linked advertiser profile\n• You can create multiple advertiser profiles per account\n• The profile includes:\n   - Name displayed on the ad\n   - Logo (profile picture/logo)\n   - Brief advertiser description\n   - Contact information',
  '٣': '3',
  'اختيار التصنيفات المناسبة': 'Select Appropriate Categories',
  '• اختر التصنيف الرئيسي بدقة (مثل: عقارات، سيارات، أجهزة)\n• حدد التصنيف الفرعي الأول (مثل: شقق للإيجار)\n• اختر التصنيف الفرعي الثانوي إن وجد (مثل: شقق مفروشة)\n• حدد الخصائص المميزة للإعلان من القائمة':
      '• Choose the main category accurately (e.g., Real Estate, Cars, Electronics)\n• Select the first subcategory (e.g., Apartments for Rent)\n• Choose a secondary subcategory if available (e.g., Furnished Apartments)\n• Specify distinctive ad features from the list',
  '٤': '4',
  'إدخال تفاصيل الإعلان': 'Enter Ad Details',
  '• اكتب عنوانًا واضحًا وجذابًا للإعلان\n• صف الإعلان بدقة وباللغة العربية الفصحى\n• حدد السعر المناسب مع العملة\n• أضف صورًا عالية الجودة (بحد أدنى 3 صور)\n   - الصور يجب أن تكون واضحة وذات دقة عالية\n   - تجنب الصور المحمية بحقوق الملكية':
      '• Write a clear and compelling ad title\n• Describe the ad accurately in standard Arabic\n• Set an appropriate price with currency\n• Add high-quality images (minimum 3)\n   - Images must be clear and high-resolution\n   - Avoid copyrighted images',
  '٥': '5',
  'تحديد الموقع الجغرافي': 'Set Geographical Location',
  '• اختر المحافظة (مثل: دمشق، حلب، اللاذقية)\n• حدد المنطقة أو الحي بدقة\n• استخدم خريطة التطبيق لتحديد الموقع الجغرافي الدقيق\n• الموقع الدقيق يساعد المشترين في الوصول إليك بسهولة':
      '• Select the governorate (e.g., Damascus, Aleppo, Latakia)\n• Specify the exact area or district\n• Use the app\'s map to pin the precise location\n• Accurate location helps buyers reach you easily',
  '٦': '6',
  'مراجعة الإعلان ونشره': 'Review and Publish Ad',
  '• راجع جميع المعلومات المدخلة قبل النشر\n• تأكد من صحة البيانات ودقتها\n• اضغط على زر "نشر الإعلان"\n• سيمر الإعلان بمرحلة مراجعة من قبل الفريق\n• سيتم إشعارك عند الموافقة على الإعلان ونشره':
      '• Review all entered information before publishing\n• Verify data accuracy and correctness\n• Click the "Publish Ad" button\n• The ad will undergo team review\n• You\'ll be notified upon approval and publication',
  'نصائح لإعلان ناجح': 'Tips for Successful Ads',
  'استخدم صورًا واضحة وجذابة من زوايا متعددة': 'Use clear, attractive photos from multiple angles',
  'اكتب وصفًا دقيقًا وشاملاً للإعلان': 'Provide an accurate and comprehensive description',
  'حدد السعر المناسب حسب السوق المحلي': 'Set a market-appropriate price',
  'تأكد من صحة معلومات التواصل': 'Ensure contact information is correct',
  'حدد التصنيفات بدقة لتظهر للجمهور المستهدف': 'Select precise categories to target the right audience',
  'لا يمكن فتح تطبيق البريد': 'Cannot open email app',
  'التواصل معنا': 'Contact Us',
  'يسعدنا تواصلكم معنا! فريق Stay in Me دائمًا متاح للإجابة على استفساراتكم ومساعدتكم في أي وقت.':
      'We\'re delighted to hear from you! The Stay in Me team is always available to answer your inquiries and assist you anytime.',
  'الهاتف': 'Phone',
  'الموقع الإلكتروني': 'Website',
  'العنوان': 'Address',
  'دمشق، سوريا': 'Damascus, Syria',
  'ساعات العمل': 'Working Hours',
  'الإبلاغ عن مشكلة': 'Report an Issue',
  'المشاكل الشائعة': 'Common Issues',
  'عدم تحميل الصور': 'Images not loading',
  'تعطل التطبيق': 'App malfunction',
  'مشكلة في الدفع': 'Payment issue',
  'مشكلة في الإعلان': 'Ad problem',
  'مشكلة في الحساب': 'Account issue',
  'أخرى': 'Other',
  'مشكلة أخرى': 'Other problem',
  'هل تحتاج إلى دعم فوري؟': 'Need immediate support?',
  'اتصل بنا الآن': 'Contact us now',
  'الشروط والأحكام': 'Terms and Conditions',
  'مرحبًا بك في تطبيق Stay in Me للإعلانات المبوبة. يرجى قراءة هذه الشروط والأحكام بعناية قبل استخدام التطبيق.':
      'Welcome to the Stay in Me classifieds app. Please read these Terms and Conditions carefully before using the application.',
  'القبول بالشروط': 'Acceptance of Terms',
  'باستخدامك تطبيق Stay in Me، فإنك توافق على الالتزام بهذه الشروط والأحكام. إذا لم توافق على أي بند من هذه الشروط، فيرجى الامتناع عن استخدام التطبيق.':
      'By using the Stay in Me app, you agree to comply with these Terms and Conditions. If you disagree with any provision, please refrain from using the app.',
  'المستخدمون المسجلون': 'Registered Users',
  'يجب أن يكون عمر المستخدم 18 عامًا على الأقل لإنشاء حساب. أنت مسؤول عن الحفاظ على سرية معلومات حسابك وكلمة المرور.':
      'Users must be at least 18 years old to create an account. You are responsible for maintaining account confidentiality and password security.',
  'نشر الإعلانات': 'Publishing Ads',
  '• يجب أن تكون الإعلانات دقيقة وصادقة\n• يحظر نشر إعلانات مخالفة للقوانين السورية\n• يحظر نشر إعلانات تتعلق بالسلاح أو المواد المخدرة\n• يحظر نشر إعلانات تحتوي على محتوى مسيء أو تمييزي':
      '• Ads must be accurate and truthful\n• Posting ads violating Syrian laws is prohibited\n• Ads related to weapons or narcotics are banned\n• Ads containing offensive or discriminatory content are forbidden',
  'المسؤولية القانونية': 'Legal Responsibility',
  'أنت المسؤول الوحيد عن المحتوى الذي تنشره على التطبيق. لا تتحمل إدارة التطبيق أي مسؤولية عن أي خسائر أو أضرار ناتجة عن استخدام التطبيق.':
      'You are solely responsible for content you publish. App management bears no responsibility for any losses or damages resulting from app usage.',
  'المعاملات المالية': 'Financial Transactions',
  'يجب إتمام جميع المعاملات المالية بين البائع والمشتري خارج التطبيق. لا تتدخل إدارة التطبيق في أي معاملات مالية ولا تتحمل مسؤوليتها.':
      'All financial transactions must be completed outside the app between buyer and seller. App management does not intervene in or assume responsibility for financial transactions.',
  'الخصوصية': 'Privacy',
  'نحن نحترم خصوصيتك ونلتزم بحماية بياناتك الشخصية. لمزيد من التفاصيل، يرجى الاطلاع على سياسة الخصوصية الخاصة بنا.':
      'We respect your privacy and are committed to protecting your personal data. For details, please see our Privacy Policy.',
  '٧': '7',
  'التعديلات': 'Modifications',
  'تحتفظ إدارة التطبيق بحق تعديل هذه الشروط والأحكام في أي وقت دون إشعار مسبق. سيتم نشر النسخة المحدثة على التطبيق.':
      'App management reserves the right to modify these Terms at any time without prior notice. Updated versions will be published on the app.',
  '٨': '8',
  'تعليق الحساب': 'Account Suspension',
  'تحتفظ إدارة التطبيق بحق تعليق أو حذف أي حساب ينتهك هذه الشروط والأحكام دون إشعار مسبق.':
      'App management reserves the right to suspend or delete accounts violating these Terms without prior notice.',
  'باستمرارك في استخدام تطبيق Stay in Me، فإنك تقر بأنك قد قرأت وفهمت ووافقت على هذه الشروط والأحكام بكاملها.':
      'By continuing to use Stay in Me, you acknowledge having read, understood, and fully agreed to these Terms and Conditions.',
  'آخر تحديث: ١ يوليو ٢٠٢٥': 'Last updated: July 1, 2025',
  'البحث والفلترة!': 'Search & Filter!',
  'عرض الإعلانات الجديدة آخر 48 ساعة': 'Show ads from last 48 hours',
  'قائمة الإعلانات التي قمت بحفظها في المفضلة للعودة إليها لاحقاً': 'Your saved favorite ads list for later access',
  'إعلانات مقترحة لك': 'Suggested Ads for You',
  'إعلانات قد تهمك بناءً على تصفحك': 'Ads you might like based on your browsing',
  'سجل المشاهدة': 'View History',
  'قائمة سجلات المشاهدات التى قمت بها للاعلانات بمختلف الأقسام': 'List of your viewed ads across all categories',
  'الإعلانات المميزة': 'Featured Ads',
  'أشهر مفاتيح البحث': 'Popular Search Keywords',
  'لا توجد مفاتيح بحث شائعة حالياً': 'No popular search keywords currently',
  'مشاهدة الكل': 'View All',
  'إظهار': 'Show',
  'الإعلانات الحديثة!': 'Recent Ads!',
  'إخفاء': 'Hide',
  'معلومات الحساب': 'Account Information',
  'المحادثات': 'Conversations',
  'نتيجة الفلترة': 'Filter Results',


////
 'الخدمات': 'Our Services',
  'الدعم': 'Support',
  'ابحث عن إعلانات...': 'Search for ads...',
  'إعلان جديد': 'New Ad',
  'تسجيل الدخول مطلوب': 'Login Required',
  'سجّل الدخول لإنشاء إعلان جديد': 'Sign in to create a new ad',
  'هذه الميزة تتطلب تسجيل الدخول': 'This feature requires login',
  'عقارات للبيع': 'Properties for Sale',
  'عقارات للإيجار': 'Properties for Rent',
  'مركبات للبيع': 'Vehicles for Sale',
  'مركبات للإيجار': 'Vehicles for Rent',
  'إعلانات': 'Ads',
  "منصة للاعلانات المبوبة الأولى في سوريا ومتخصصة في إعلانات المركبات بمختلف أنوعا والعقارات": "Syria's first classifieds platform specialized in vehicle and property listings",
  'روابط سريعة': 'Quick Links',
  'تواصل معنا': 'Contact Us',
  'اتصل بنا': 'Call Us',
  'دمشق،  شارع الرئيسي': 'Damascus, Main Street',
  '24/7 خدمة العملاء': '24/7 Customer Service',
  '© 2025 Stay in me. جميع الحقوق محفوظة': '© 2025 Stay in me. All rights reserved',
  'إعدادات الحساب': 'Account Settings',
  'معلوماتي الشخصية': 'Personal Information',
  'إدارة معلومات الحساب الأساسية': 'Manage basic account information',
  'الأمان': 'Security',
  'تغيير كلمة المرور': 'Change Password',
  'المحادثات والرسائل مع مختلف المعلنين': 'Chats and messages with advertisers',
  'إعدادات الإعلانات': 'Ads Settings',
  'إضافة إعلان جديد إلى المنصة': 'Add new ad to the platform',
  'عرض وتعديل الإعلانات المنشورة': 'View and edit published ads',
  'الإعلانات قيد المراجعة': 'Ads Under Review',
  'إعدادات المعلنين': 'Advertisers Settings',
  'عرض وتعديل بيانات المعلنين': 'View and edit advertisers data',
  'إضافة معلن جديد إلى الحساب': 'Add new advertiser to account',
  'المفضلات والتاريخ': 'Favorites & History',
  'عرض الإعلانات المفضلة': 'View favorite ads',
  'عرض الإعلانات التي شاهدتها مؤخرًا': 'View recently viewed ads',
  'إعدادات المظهر': 'Appearance Settings',
  'تغيير لغة التطبيق': 'Change app language',
  'تغيير العملة المستخدمة': 'Change currency',
  'التغيير بين الوضع الفاتح والداكن': 'Toggle light/dark mode',
  'تعرف على شركتنا ورسالتنا': 'About our company and mission',
  'سياسات الاستخدام وشروط الخدمة': 'Usage policies and terms of service',
  'اختر الباقة المناسبة لاحتياجاتك': 'Choose the right package for your needs',
  'كيفية نشر الإعلانات على المنصة': 'How to post ads on the platform',
  'تواصل مع فريق الدعم': 'Contact support team',
  'بلغنا عن أي مشكلة تواجهك': 'Report any issues you encounter',
  'رسالتنا': 'Our Mission',
  'تقديم منصة شاملة وآمنة تتيح للمستخدمين التواصل التجاري بسلاسة وثقة، مع الحفاظ على خصوصية وأمان مستخدمينا.': 'Providing a secure platform for seamless commercial interactions while protecting user privacy.',
  "الباقات": "Packages",
  '• يجب أن تكون الإعلانات دقيقة وصادقة\n• يحظر نشر إعلانات مخالفة للقوانين\n• يحظر نشر إعلانات تتعلق بالسلاح أو المواد المخدرة\n• يحظر نشر محتوى مسيء أو تمييزي': 
  '• Ads must be accurate and honest\n• Illegal ads are prohibited\n• Ads for weapons or drugs are banned\n• Offensive or discriminatory content is not allowed',
  'للاستفسارات أو المساعدة، يرجى التواصل مع دعم التطبيق عبر البريد الإلكتروني: support@stayinme.com': 
  'For inquiries or assistance, contact app support at: support@stayinme.com',
  'الأحد - الخميس': 'Sunday - Thursday',
  'الجمعة': 'Friday',
  'السبت': 'Saturday',
  '9:00 ص - 5:00 م': '9:00 AM - 5:00 PM',
  '10:00 ص - 2:00 م': '10:00 AM - 2:00 PM',
  'عطلة رسمية': 'Official holiday',
  'نحن نعتذر عن أي إزعاج تواجهه. يرجى وصف المشكلة التي واجهتها بدقة لمساعدتنا على حلها.':
  'We apologize for any inconvenience. Please describe the issue accurately to help us resolve it.',
  'بريد إلكتروني غير محدد': 'Email not specified',
  'تفاصيل الحساب': 'Account Details',
  'اللغة المفضلة': 'Preferred Language',
  'الانجليزية': 'English',
  'آخر نشاط': 'Last Activity',
  'الان': 'Now',
  'حالة التحقق': 'Verification Status',
  'نشط': 'Active',
  'المعلن': 'Advertiser',
  'لا توجد رسائل بعد': 'No messages yet',
  'أنا': 'Me',
  'اكتب رسالة...': 'Type a message...',
  'ص': 'AM',
  'م': 'PM',
  'اختر محادثة لعرضها': 'Select a conversation to view',
  'لا توجد محادثات': 'No conversations',
  'بدء محادثة جديدة': 'Start new conversation',
  'إزالة من السجلات': 'Remove from history',
  'قائمة': 'List',
  'شبكة': 'Grid',
  'اختر العملة المفضلة': 'Choose preferred currency',
  'سيتم عرض جميع الأسعار بالعملة التي تختارها': 'All prices will be shown in your selected currency',
  'سيتم عرض جميع الأسعار بالعملة المحددة. يمكنك تغييرها في أي وقت من هذه الصفحة.': 
  'All prices will be displayed in the selected currency. You can change it anytime from this page.',
  'اختر لغتك المفضلة': 'Choose your preferred language',
  'سيتم عرض التطبيق باللغة التي تختارها': 'The app will be displayed in your selected language',
  'رمز اللغة:': 'Language Code:',
  'تم تغيير اللغة. سيتم تطبيق التغيير على جميع أجزاء التطبيق.': 
  'Language changed. The change will apply to all app sections.',
  "اضف إلى مفضلتي": "Add to favorites",
  'السعر:': 'Price:',
  'إرسال رسالة': 'Send Message',
  'فيديو': 'Video',
  'جاري تحميل الفيديو...': 'Loading video...',
  'تعذر تحميل الفيديو': 'Failed to load video',
  'إعادة المحاولة': 'Retry',
  'تعذر تحميل الصورة': 'Failed to load image',
  'صورة': 'Image',
  'عرض': 'View',
  'من': 'of',
  'نتيجة': 'result',
  'الأحدث': 'Newest',
  'الأقدم': 'Oldest',
  'الأرخص': 'Cheapest',
  'الأغلى': 'Most Expensive',
  'الأعلى مشاهدة': 'Most Viewed',
  'الفرز:': 'Sort:',
  'عرض شبكي': 'Grid View',
  'عرض قائمة': 'List View',
  'لم نعثر على إعلانات': 'No ads found',
  'جرب تغيير فلترات البحث أو معايير التصفية': 'Try changing search filters or criteria',
  'إعادة تعيين الفلاتر': 'Reset Filters',
  'الإجمالي:': 'Total:',
  'إعلان': 'ad',
  'حذف النتائج النتائج': 'Clear Results',
  'مسح الفلاتر': 'Clear Filters',
  'البحث بالكلمات': 'Keyword Search',
  'التصنيفات': 'Categories',
  'التصنيف الفرعي الثانوي': 'Secondary Subcategory',
  'المسافة من موقعك الحالي:': 'Distance from your location:',
  'حصر الاعلانات': 'Filter Ads',
  'تحديث موقعك الحالي': 'Update current location',
  'اختر المسافة': 'Select Distance',
  'تحذير': 'Warning',
  'يرجى تحديد المسافة والتأكد من تفعيل الموقع': 'Please select distance and ensure location is enabled',
  'آخر 24 ساعة': 'Last 24 hours',
  'كل الأوقات': 'All time',
  'إعادة تعيين كلمة المرور': 'Reset Password',
  'أدخل بريدك الإلكتروني لإرسال رمز التحقق وإعادة تعيين كلمة المرور': 
  'Enter your email to send verification code and reset password',
  'كلمة المرور الجديدة': 'New Password',
  'سيتم إرسال رمز التحقق إلى بريدك الإلكتروني لتأكيد هويتك': 
  'Verification code will be sent to your email to confirm identity',
      'أحدث الإعلانات':'new Ads',
      'عن الشركة':'about us',
           "منصة للاعلانات المبوبة الأولى في سوريا ومتخصصة في إعلانات المركبات بمختلف أنواعها والعقارات": "The first classifieds platform in Syria, specializing in vehicle and real estate ads of all kinds.",


};